- ansible.windows.win_domain_membership:
      dns_domain_name: "{{ dns_domain_name }}"
      domain_admin_user: "{{ domain_admin_user }}"
      domain_admin_password: "{{ domain_admin_password }}"
      domain_ou_path: "{{ domain_ou_path }}"
      state: "{{ state }}"
  register: "{{ register }}"

- ansible.windows.win_reboot:
  when: domain_state.reboot_required
