- name: Install all security, critical, and rollup updates without a scheduled tasks
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: installed
    register: Output
    log_path: C:\ansible_wu.txt
    reboot: yes
