---
# vars file for win-task-deploy_iis
iisUser1: vcrx\AppLWR
IrisAgentUser: vcrx\svcIrisLWR
IrisAgentPasswd: ""
sureScriptsUser: vcrx\svcScriptEngLWR
sureScriptsPasswd: ""
domainAdmins: vcrx\Domain Admins
devopsAdmins: vcrx\IT DevOps Admins
devAdmins: vcrx\IT Developers
qaAdmins: vcrx\IT QA
svcDeploy: vcrx\svcDeploy
siteFiles: site-files/cofy-site-files.zip
unzipSource: C:\temp\cofy-site-files.zip
unzipServicesSource: C:\temp\cofy-site-files\Services.zip
unzipServicesDest: C:\TXMD\
tempPath: C:\temp\
txmdPath: C:\TXMD
appPath: C:\TXMD\APPS
apiPath: C:\TXMD\API
webPath: C:\TXMD\WEB
coracareCertPath: C:\temp\cofy-site-files\coracare.vitacarerx.com.pfx
apiCertPath: C:\temp\cofy-site-files\api.coracare.vitacarerx.com.pfx
certPasswd: Cw4Nh6tbxHS2
dotnetcoreEnv: COFY
logsPath: C:\CoraCareLogs 
svcPath: C:\TXMD\Services
filesPath: C:\TXMD\Files
svcName: TXMD.IrisAgent
IrisAgentSvcPath: C:\TXMD\Services\IrisAgent\IrisAgentService.exe
IrisAgentPath: C:\TXMD\FILES\IrisAgent\
IrisAgentDbSrc: site-files/IrisAgent/

