---
- hosts: database
  become: true
  tasks:
   - name: install tools
     apt: name={{item}} state=present
     with_items:
     - python-mysqldb
     - mysql-server
     tags: [ 'packages' ]

   - name: ensure mysql is listening on all ports
     lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
     notify: restart mysql
     tags: [ 'service' ]

   - name: ensure mysql is started
     service: name=mysql state=started enabled=yes
     tags: [ 'service' ]

   - name: create demo database
     mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
     tags: [ 'configure' ]

  handlers:
   - name: restart mysql
     service: name=mysql state=restarted
     tags: [ 'service' ]
