---
# Bring stack down
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: database
  become: true
  gather_facts: false
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80

- hosts: loadbalancer
  become: true
  tasks:
    - shell: service=nginx state=started
    - wait_for: port=80
