---
- hosts: windows
  gather_facts: false
  tasks:
    - name: Installing...GoogleChrome, notepadplusplus, 7zip
      win_chocolatey:
        name:
          - notepadplusplus
          - googlechrome
          - 7zip
          state: present
