- hosts: kube
  become: true

  tasks:
    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname
