---
- hosts: windows
  become: true
  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        log_path: C:\ansible_wu.txt
        reboot: yes
