---
- name: Run Chocolately Script
  hosts: windows
  gather_facts: false

  tasks:
  - name: Create directory structure
    win_file:
      path: C:\Temp
      state: directory

  - name: copy choco script onto windows nodes
    win_copy:
      src: /root/myplatform/choco.ps1
      dest: C:\Temp\choco-apps.ps1

  - name: run chocolatey powershell script
    win_shell: C:\Temp\choco.ps1 C:\Temp\choco-script-install-log.txt
