---
- hosts: windows
  gather_facts: false
  tasks:
    - win_chocolatey_feature:
      name: useEnhancedExitCodes
      state: disabled
    - name: Installing...GoogleChrome, notepadplusplus, 77zip
      win_chocolatey:
        name:
           - notepadplusplus
           - googlechrome
           - 7zip
           - treesize
        state: present
